/** Anzeigenamen für Tools (Client-seitig, ohne Server-Registry zu importieren). */
const LABELS: Record<string, string> = {
  "plan.update": "Plan aktualisiert",
  "tasks.list": "Aufgaben geladen",
  "tasks.create": "Aufgabe erstellen",
  "tasks.update": "Aufgabe ändern",
  "tasks.complete": "Aufgabe abschließen",
  "tasks.delete": "Aufgabe löschen",
  "projects.list": "Projekte geladen",
  "projects.get": "Projekt geladen",
  "projects.create": "Projekt erstellen",
  "projects.update": "Projekt ändern",
  "notes.create": "Notiz speichern",
  "reminders.create": "Erinnerung erstellen",
  "reminders.list": "Erinnerungen geladen",
  "notifications.create": "Benachrichtigung",
  "calendar.listEvents": "Kalender geprüft",
  "calendar.findFreeSlots": "Freie Zeiten gesucht",
  "calendar.checkConflicts": "Konflikte geprüft",
  "calendar.createEvent": "Kalendertermin erstellen",
  "calendar.createEvents": "Kalendertermine erstellen",
  "calendar.updateEvent": "Kalendertermin ändern",
  "calendar.deleteEvent": "Kalendertermin löschen",
  "exams.list": "Prüfungen gesucht",
  "exams.create": "Prüfung erfassen",
  "exams.update": "Prüfung ändern",
  "exams.planStudy": "Lernplan erstellt",
  "email.search": "E-Mails durchsucht",
  "email.read": "E-Mail gelesen",
  "email.thread": "E-Mail-Verlauf gelesen",
  "email.labels": "Gmail-Labels geladen",
  "email.importAttachment": "Anhang importieren",
  "email.createDraft": "E-Mail-Entwurf erstellen",
  "email.send": "E-Mail senden",
  "documents.search": "Dokumente durchsucht",
  "documents.list": "Dokumente geladen",
  "documents.read": "Dokument gelesen",
  "documents.create": "Dokument erzeugen",
  "documents.importFromDrive": "Drive-Datei importieren",
  "drive.search": "Google Drive durchsucht",
  "onenote.search": "OneNote durchsucht",
  "onenote.listNotebooks": "OneNote-Notizbücher geladen",
  "onenote.read": "OneNote-Seite gelesen",
  "onenote.sync": "OneNote indexiert",
  "school.sync": "Schulplattform geprüft",
  "web.search": "Web durchsucht",
  "web.open": "Webseite gelesen",
  "browser.open": "Seite im Browser geöffnet",
  "browser.click": "Im Browser klicken",
  "browser.type": "Im Browser eingeben",
  "browser.select": "Im Browser auswählen",
  "browser.download": "Datei herunterladen",
  "memory.search": "Gedächtnis durchsucht",
  "memory.store": "Im Gedächtnis gespeichert",
  "search.global": "Überall gesucht",
  "visualization.create": "Visualisierung erstellt",
};

export const toolLabel = (name: string) => LABELS[name] ?? name;
export function ToolLabel({ name }: { name: string }) {
  return <>{toolLabel(name)}</>;
}
